export const VALID_GENDERS = ['MALE', 'FEMALE', 'OTHER'];
export const VALID_MARITAL_STATUSES = ['SINGLE', 'MARRIED', 'DIVORCED'];
export const VALID_DEPARTMENTS = ['ENGINEERING', 'MARKETING', 'FINANCE', 'HR', 'SALES'];
export const VALID_EMPLOYMENT_TYPES = ['PERMANENT', 'CONTRACT', 'TEMPORARY', 'INTERN'];
export const VALID_STATUSES = ['ACTIVE', 'INACTIVE', 'ON_LEAVE', 'TERMINATED'];
export const VALID_ACCOUNT_TYPES = ['SAVINGS', 'CURRENT', 'NRI'];
